### ISSUE TITLE
Prevent adding a validator logo from people unrelated to the validator

### ISSUE THREAD

**Issue by Antropocosmist** [cosmostation/chainlist#1230]
Unknown github user created a pool request to add logo of POSTHUMAN validator in Kava:
https://github.com/cosmostation/chainlist/commits?author=qraga77

POSTHUMAN validator doesn't have validator in Kava

The list of our core-team members are available here:
https://github.com/Validator-POSTHUMAN/core-team

**Comment by wannabit-yongjoo** [comment]
Thanks for notification.
We add that op-address with van list.

display moniker no more, and not contain's validators statistics
