### ISSUE TITLE
Add KUJIRA

### ISSUE THREAD

**Issue by th3nyst1c** [cosmostation/chainlist#1253]
Add [Kujira Network](https://kujira.network/) (kaiyo-1) again.

**Comment by th3nyst1c** [comment]
Not listing Kujira means penalizing both Kujira and the chains connected to it. If you want to offer the best possible experience for users of the cosmos ecosystem you cannot censor chains at will.

**Comment by th3nyst1c** [comment]
For example, if I wanted to monitor my IBC activities I couldn't do it well, because every time I switch to Kujira I have to change explorer.

**Comment by zrbecker** [comment]
Isn't this Kuji? https://github.com/cosmostation/chainlist/tree/main/chain/kujira What is missing here?

**Comment by wannabit-yongjoo** [comment]
Mintscan previously deleted Kujira. But it is not supported now.
Now only support IBC information with another chains
