### ISSUE TITLE
Update chain names about Terra..

### ISSUE THREAD

**Issue by wannabit-yongjoo** [cosmostation/chainlist#2008]
We using 

old terra as (terra-classic)

hrad forked terra as (terra)

what is better?

**Comment by stamper-dev** [comment]
We will using

OLD TERRA   -> terra-classic
NEW TERRA   -> terra

like ethereum and ethereum-classic

no modify at all please

**Comment by stamper-dev** [comment]
For terra-classic:
- channel-72
- channel-78488

For terra:
- channel-251
- channel-341
- channel-21671
