### ISSUE TITLE
CROWP ERC20 Token not show on mintscan

### ISSUE THREAD

**Issue by forbesus** [cosmostation/chainlist#2042]
I created pull request #2012 to register my erc20 token to minscan but my token is not displayed on mintscan

**Comment by forbesus** [comment]
And I added #1583 my token but It's not displayed on mint scan osmosis asset

**Comment by wannabit-yongjoo** [comment]
Hi @forbesus 
Confirmed front side issue.
Thanks a lot for reporting.

Dev team fixing it now.
After fix I will comment here again

**Comment by wannabit-yongjoo** [comment]
in osmosis chain. 
the ibc denom is zero balance.

If you send tiny amount of CROWDP to osmosis via IBC
you can check in osmosis asset tab


https://lcd.osmosis.zone/cosmos/bank/v1beta1/supply/by_denom?denom=ibc/B87F0F5255CC658408F167C2F7B987A8D914622E1F73BCC267406360588F2B1E
![스크린샷 2024-11-21 오후 8 37 53](https://github.com/user-attachments/assets/f7a881f2-f8af-4652-8fb0-a35853fb0d23)

**Comment by forbesus** [comment]
Hello @wannabit-yongjoo 
I mentioned wrong pr before

I created 2 prs and latest pr is here #1601 

Would you check again?

**Comment by wannabit-yongjoo** [comment]
assets.json is not using.
we migrate to assets_2.json and using this for mintscan and wallet, etc

I think now json files look all fine.

**Comment by wannabit-yongjoo** [comment]
`https://lcd.osmosis.zone/cosmos/bank/v1beta1/supply?pagination.limit=5100`

I checked you already ibc sent CROWDP evmos to osmosis.

but you can check upper lcd, there is no  your ibc denom (ibc/B87F0F5255CC658408F167C2F7B987A8D914622E1F73BCC267406360588F2B1E)

I think you sent ibc back or pull all amount your pool.


we using the top lcd(on-chain) query, but your coin denom not found -> so not display mintscan now.

**Comment by wannabit-yongjoo** [comment]
![스크린샷 2024-11-22 오후 4 35 59](https://github.com/user-attachments/assets/2f214c8e-263a-419f-b4cc-5ba81f67460f)
got it.
sorry for miss understanding.
now display in osmosis.

if you ok. please close this issue.
thanks a lot.

**Comment by forbesus** [comment]
thank you for your support
