### ISSUE TITLE
Use keybase.io identity to get logo instead of PR!

### ISSUE THREAD

**Issue by atomlab** [cosmostation/chainlist#229]
Hello. Use keybase.io identity from validator metadata to get logo instead of PR. This is much more convenient for validators!
The validator sends metadata information to the blockchain when registering a validator account.

Example for Cosmos-like validators
```
osmosisd tx staking create-validator \
--website="<website>" \
--details='<desc>' \
--identity=<keybase.io identity > \
...
```

[Doc](https://hub.cosmos.network/main/validators/validator-setup.html)

> The --identity can be used as to verify identity with systems like Keybase or UPort. When using Keybase, --identity should be populated with a 16-digit string that is generated with a [keybase.io (opens new window)](https://keybase.io/) account. It's a cryptographically secure method of verifying your identity across multiple online networks. The Keybase API allows us to retrieve your Keybase avatar. This is how you can add a logo to your validator profile.

# How to get Logo URL by public identity key

`key_suffix=<identity>`

```
$ curl -s "https://keybase.io/_/api/1.0/user/lookup.json?key_suffix=E73AFD8985423B14&fields=pictures" | jq .them
[
  {
    "id": "5764d5f1a9c055df1c71a9c71e993519",
    "pictures": {
      "primary": {
        "url": "https://s3.amazonaws.com/keybase_processed_uploads/128efcca8fffd52fed0cae7aa9f25d05_360_360.jpg",
        "source": null
      }
    }
  }
]
```

**Comment by wannabit-yongjoo** [comment]
Hi @atomlab 
Thanks a lot for good suggest.
We used that way but changed current way cuz some reasons.
