### ISSUE TITLE
Logo not updating despite the PR having been merged

### ISSUE THREAD

**Issue by Jackson-DKMG** [cosmostation/chainlist#402]
Hi, 

I made a PR a few days ago to update the Terra Classic logo for TerraCVita, which was merged (https://github.com/cosmostation/chainlist/pull/377)

However, the logo did not update on the restake app (https://restake.app/terra/terravaloper1uymwfafhq8fruvcjq8k67a29nqzrxnv9m6m427) and still points to https://raw.githubusercontent.com/cosmostation/cosmostation_token_resource/master/moniker/terra/terravaloper1uymwfafhq8fruvcjq8k67a29nqzrxnv9m6m427.png.

Is that the expected behavior?

Regards,
Thomas

**Comment by wannabit-yongjoo** [comment]
Hi @Jackson-DKMG 
This repo using only for mintscan and cosmostaion apps.
I think you can PR[ this](https://github.com/terra-money/validator-images) and [this](https://github.com/terra-money/validator-profiles)  repo
