### ISSUE TITLE
Validator moniker change not reflected on Mintscan

### ISSUE THREAD

**Issue by freak12techno** [cosmostation/chainlist#458]
Greetings.
I am operating the following Cosmos Hub validator: https://www.mintscan.io/cosmos/validators/cosmosvaloper1xqz9pemz5e5zycaa89kys5aw6m8rhgsvw4328e
I did a rebranding shortly after it went active, from `freak12techno` to `Quokka Stake`.
But somehow the link in the "Additional Info" block leads to this page https://hub.mintscan.io/validators/stats/freak12techno/cosmos/cosmosvaloper1xqz9pemz5e5zycaa89kys5aw6m8rhgsvw4328e, which includes my older moniker.
Is there anything I should/can do to get it updated?

(Sorry if this is a wrong repository to report it to, didn't find any other one that suits it.)

**Comment by wannabit-yongjoo** [comment]
Hi @freak12techno 
Thanks a lot with bug report.

Now we upgrading mintscan hub, so fix it soon.
