### ISSUE TITLE
Our validators' website doesn't appear in the Mintscan

### ISSUE THREAD

**Issue by caotre** [cosmostation/chainlist#729]
Our validators' website doesn't appear in the Mintscan but it appears in the Ping.
My validator is https://ping.pub/cosmos/staking/cosmosvaloper13ql36flc4cdjhx08hke5vpr4dyv03aafnmvtnc, https://www.mintscan.io/cosmos/validators/cosmosvaloper13ql36flc4cdjhx08hke5vpr4dyv03aafnmvtnc
I think Mintscan's code doesn't understand the .ventures domain.

**Comment by Kwonhyukjoon** [comment]
Thanks for letting me know I will inform the Mintscan development team.

**Comment by Kwonhyukjoon** [comment]
We'll fix it. Thank you!
