### ISSUE TITLE
Missed blocks counter on Neutron

### ISSUE THREAD

**Issue by caotre** [cosmostation/chainlist#841]
My validator is TienThuatToan (https://www.mintscan.io/neutron/ics-validators/neutronvaloper13ql36flc4cdjhx08hke5vpr4dyv03aafgdg9rg). 
Neutrond shows that my validator has missed 722 blocks. But I see that Mintscan hasn't recorded any missed blocks since Neutron launched. Can you check it?
Please take the look https://imgur.com/FpT0ocd.
Smartstake also records missed blocks https://analytics.smartstake.io/neutron/val/cosmosvaloper1ff0dw8kawsnxkrgj7p65kvw7jxxakyf8n583gx

**Comment by jeongeunlee1209** [comment]
Thank you for informing us regarding the missed block data on the mintscan.
As it was addressed from the email from the support@cosmostation.io, we are checking this with our development team.
If we have any updates on it, we will inform you through the email. So, we will close the issue. 
Once again, thank you and will let you know any updates through the email.
